enum EFlatReservation { // 1,16,3,2,33,35
  OralReservation = 1,
}

export enum EFlatStatusKeys {
  AgreementSigned = 36,
  BookingConfirmedReselection = 35,
  BookDeveloper = 34,
  BookingConfirmed = 33,
  Terminated = 32,
  OnTermination = 31,
  WithdrawnFromSale = 30,
  SpecialStatus = 29,
  Contractor = 28,
  Pass = 27,
  Suspension = 25,
  Registered = 24,
  BookingSpecial = 23,
  ForSale = 21,
  BookingByInstallments = 16,
  Sold = 15,
  Installment = 14,
  OnRegistration = 13,
  Decoration = 12,
  ReservationSecondary = 6,
  BookingWithoutPayment = 5,
  BookingPaid = 4,
  BookingContractor = 3,
  BookingMortgage = 2,
  VerbalBooking = 1,
}